---
- name: 'build and push the Chat UI Docker image to ECR'
  include_role:
    name: 'ringier.aws_cicd.build_push_docker_image'
  vars:
    ecr_repository_name: '{{ chat_ui_ecr_repository_name }}'
    code_path: '{{ playbook_dir }}/../app/a2a-inspector'
    adhoc_deploy: true

- name: 'set chat ui docker image fact'
  set_fact:
    chat_ui_docker_image: '{{ docker_image_full_name_and_tag }}'

- name: 'set cloudformation template'
  set_fact:
    cloudformation_template: '{{ role_path }}/files/cf-ecs.yml'

- name: 'deploy the ECS and adjacent resources'
  include_role:
    name: 'ringier.aws_cicd.run_cloudformation'
  vars:
    stack_name: '{{ env }}-{{ project_id }}-{{ software_component }}-chat-ui-ecs'
    template: '{{ cloudformation_template }}'
