
- name: 'check if secret key already exists in SSM'
  no_log: '{{ ansible_verbosity < 3 }}'
  set_fact:
    chat_ui_secret_key_from_ssm: "{{ lookup('amazon.aws.aws_ssm', ssmkey_chat_ui_secret_key, region=aws_region, on_missing='skip') }}"

- name: 'generate and upload Chat UI secret key to SSM if needed'
  when: chat_ui_secret_key_from_ssm == ''
  block:
    - name: 'generate random password if needed'
      no_log: '{{ ansible_verbosity < 3 }}'
      set_fact:
        chat_ui_secret_key: "{{ lookup('password', '/dev/null', length=32, chars=['ascii_letters', 'digits', 'punctuation']) }}"

    - name: 'upload Chat UI secret key to SSM'
      ringier.aws_cicd.ssm_parameter:
        region: '{{ aws_region }}'
        overwrite_value: 'never'
        name: '{{ ssmkey_chat_ui_secret_key }}'
        description: 'Secret key for the Chat UI component of RC+/Alloy'
        string_type: 'SecureString'
        key_id: 'alias/gov-rcplus-devops-secrets'
        value: '{{ chat_ui_secret_key }}'
        tags:
          Name: '{{ env }}-{{ project_id }}-chat-ui-secret-key'
          Project: '{{ project_id }}'
          Environment: '{{ env }}'
          Repository: '{{ git_info.repo_name }}'
          Version: '{{ project_version }}'

- name: 'upload Chat UI OIDC client secret to SSM'
  ringier.aws_cicd.ssm_parameter:
    overwrite_value: 'changed'
    name: '{{ ssmkey_chat_ui_oidc_client_secret }}'
    description: 'The OIDC client secret for the Chat UI component of RC+/Alloy'
    string_type: 'SecureString'
    value: '{{ chat_ui_oidc_client_secret }}'
    tags:
      Name: '{{ env }}-{{ project_id }}-chat-ui-oidc-client-secret'
      Project: '{{ project_id }}'
      Environment: '{{ env }}'
      Repository: '{{ git_info.repo_name }}'
      Version: '{{ project_version }}'
