

- name: 'upload Agent Creator OIDC client secret to SSM'
  ringier.aws_cicd.ssm_parameter:
    overwrite_value: 'changed'
    name: '{{ ssmkey_agent_creator_oidc_client_secret }}'
    description: 'The OIDC client secret for the Agent Creator component of RC+/Alloy'
    string_type: 'SecureString'
    value: '{{ agent_creator_oidc_client_secret }}'
    tags:
      Name: '{{ env }}-{{ project_id }}-agent-creator-oidc-client-secret'
      Project: '{{ project_id }}'
      Environment: '{{ env }}'
      Repository: '{{ git_info.repo_name }}'
      Version: '{{ project_version }}'
