---
- name: 'set cloudformation template'
  set_fact:
    cloudformation_template: '{{ role_path }}/files/cf-cloudfront.yml'

- name: 'deploy CloudFront distribution'
  include_role:
    name: 'ringier.aws_cicd.run_cloudformation'
  vars:
    stack_name: '{{ env }}-{{ project_id }}-{{ software_component }}-cloudfront-shared-resources'
    template: '{{ cloudformation_template }}'
