---
agent_creator_client_id: 'agent-creator'
agent_creator_public_api_port: 8080
agent_creator_fqdn: 'agent-creator.{{ base_domain }}'
agent_creator_task_cpu: 512
agent_creator_task_memory: 1024
agent_creator_ecr_repository_name: '{{ env }}-{{ project_id }}-{{ software_component }}-agent-creator'
