# Secret for Orchestrator Agent
apiVersion: v1
kind: Secret
metadata:
  name: orchestrator-secrets
  labels:
    app: orchestrator-agent
    app.kubernetes.io/part-of: nannos
type: Opaque
stringData:
  AZURE_OPENAI_API_KEY: YOUR_AZURE_OPENAI_API_KEY
  OIDC_CLIENT_SECRET: YOUR_ORCHESTRATOR_OIDC_CLIENT_SECRET
  POSTGRES_PASSWORD: YOUR_DOCSTORE_PG_PASSWORD
---
# Secret for Playground Backend
apiVersion: v1
kind: Secret
metadata:
  name: console-secrets
  labels:
    app: console
    app.kubernetes.io/part-of: nannos
type: Opaque
stringData:
  # Secrets from ECS TaskDefinition
  SECRET_KEY: YOUR_SECRET_KEY
  OIDC_CLIENT_SECRET: YOUR_CONSOLE_OIDC_CLIENT_SECRET
  POSTGRES_PASSWORD: YOUR_CONSOLE_POSTGRES_PASSWORD
  KEYCLOAK_ADMIN_CLIENT_SECRET: YOUR_KEYCLOAK_ADMIN_CLIENT_SECRET
---
# Secret for Agent Runner
apiVersion: v1
kind: Secret
metadata:
  name: agent-runner-secrets
  labels:
    app: agent-runner
    app.kubernetes.io/part-of: nannos
type: Opaque
stringData:
  AZURE_OPENAI_API_KEY: YOUR_AZURE_OPENAI_API_KEY
  OIDC_CLIENT_SECRET: YOUR_AGENT_RUNNER_OIDC_CLIENT_SECRET
  POSTGRES_PASSWORD: YOUR_AGENT_RUNNER_POSTGRES_PASSWORD
---
# Secret for Agent Creator
apiVersion: v1
kind: Secret
metadata:
  name: agent-creator-secrets
  labels:
    app: agent-creator
    app.kubernetes.io/part-of: nannos
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: YOUR_AGENT_CREATOR_OIDC_CLIENT_SECRET
---
# Secret for Slack Client
apiVersion: v1
kind: Secret
metadata:
  name: client-slack-secrets
  labels:
    app: client-slack
    app.kubernetes.io/part-of: nannos
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: YOUR_SLACK_CLIENT_OIDC_CLIENT_SECRET
  POSTGRES_PASSWORD: YOUR_SLACK_CLIENT_POSTGRES_PASSWORD
  V2_COOKIE_SECRET: YOUR_V2_COOKIE_SECRET (RANDOM STRING)
---
# Secret for Email Client
apiVersion: v1
kind: Secret
metadata:
  name: client-email-secrets
  labels:
    app: client-email
    app.kubernetes.io/part-of: nannos
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: YOUR_EMAIL_CLIENT_OIDC_CLIENT_SECRET
  POSTGRES_PASSWORD: YOUR_EMAIL_CLIENT_POSTGRES_PASSWORD
---
# Secrets for Voice Agent
apiVersion: v1
kind: Secret
metadata:
  name: voice-agent-secrets
  labels:
    app: voice-agent
    app.kubernetes.io/part-of: nannos
type: Opaque
stringData:
  GCP_KEY: YOUR_GCP_KEY_JSON_STRING
  LANGSMITH_API_KEY: YOUR_LANGSMITH_API_KEY
  OIDC_CLIENT_SECRET: YOUR_VOICE_AGENT_OIDC_CLIENT_SECRET
  TWILIO_ACCOUNT_SID: YOUR_TWILIO_ACCOUNT_SID
  TWILIO_API_KEY: YOUR_TWILIO_API_KEY
  TWILIO_API_SECRET: YOUR_TWILIO_API_SECRET
  TWILIO_VERIFY_API_KEY: YOUR_TWILIO_VERIFY_API_KEY
  TWILIO_VERIFY_API_SECRET: YOUR_TWILIO_VERIFY_API_SECRET
---
# Secret for Google Chat Client
apiVersion: v1
kind: Secret
metadata:
  name: client-google-chat-secrets
  labels:
    app: client-google-chat
    app.kubernetes.io/part-of: nannos
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: YOUR_GOOGLE_CHAT_CLIENT_OIDC_CLIENT_SECRET
  POSTGRES_PASSWORD: YOUR_GOOGLE_CHAT_CLIENT_POSTGRES_PASSWORD
  GCP_SA_JSON_KEY_GCP_PROJECT_NAME: YOUR_GCP_SA_JSON_KEY_GCP_PROJECT_NAME
