---
- name: 'copy ringier-a2a-sdk into foundry-jira-a2a-server directory'
  block:
    # NOTE: necessary until we will distribute ringier-a2a-sdk via a package index
    - name: 'copy ringier-a2a-sdk'
      synchronize:
        src: '{{ playbook_dir }}/../app/ringier-a2a-sdk/'
        dest: '{{ playbook_dir }}/../app/foundry-jira-a2a-server/ringier-a2a-sdk/'
        rsync_opts:
          - '--exclude=__pycache__'
          - '--exclude=*.pyc'
          - '--exclude=.venv'
          - '--exclude=.git'
          - '--exclude=.pytest_cache'
          - '--exclude=tests'
          - '--exclude=.mypy_cache'
          - '--exclude=.ruff_cache'

    - name: 'build and push the Foundry Jira Agent Docker image to ECR'
      include_role:
        name: 'ringier.aws_cicd.build_push_docker_image'
      vars:
        ecr_repository_name: '{{ foundry_jira_agent_ecr_repository_name }}'
        code_path: '{{ playbook_dir }}/../app/foundry-jira-a2a-server'
        docker_build_args:
          API_PORT: '{{ foundry_jira_agent_public_api_port }}'
  always:
    - name: 'clean up copied ringier-a2a-sdk'
      file:
        path: '{{ playbook_dir }}/../app/foundry-jira-a2a-server/ringier-a2a-sdk'
        state: absent

- name: 'set foundry jira agent docker image fact'
  set_fact:
    foundry_jira_agent_docker_image: '{{ docker_image_full_name_and_tag }}'

- name: 'set cloudformation template'
  set_fact:
    cloudformation_template: '{{ role_path }}/files/cf-ecs.yml'

- name: 'deploy the ECS and adjacent resources'
  include_role:
    name: 'ringier.aws_cicd.run_cloudformation'
  vars:
    stack_name: '{{ env }}-{{ project_id }}-{{ software_component }}-foundry-jira-agent-ecs'
    template: '{{ cloudformation_template }}'
