---
  - name: 'Infrastructure for Alloy Agents Framework'
    hosts: 'localhost'
    connection: 'local'
    collections: 'ringier.aws_cicd'
    gather_facts: false
    vars:
      aws_region: 'eu-central-1'
      project_id: 'nannos'
      project_version: 0.1.1
      software_component: 'infrastructure-agents'
    pre_tasks:
      - fail: msg='specify an environment (dev,stg,prod)'
        when: env not in ['dev', 'stg', 'prod']
      - include_vars: 'environment_vars/{{ env }}.yml'
    roles:
      - 'ringier.aws_cicd.init_workspace'
      - 'basis'
      - 'orchestrator'
      - 'playground'
      - 'agent-creator'
      - 'alloy-agent'
      - 'ringier.aws_cicd.del_workspace'
