"""Fixtures for integration tests that make real LLM calls.

These tests require actual cloud credentials to run:
- Bedrock: AWS credentials (via boto3 default chain)
- Azure OpenAI: AZURE_OPENAI_ENDPOINT + AZURE_OPENAI_API_KEY
- Vertex AI: GCP_KEY (JSON service account) + GCP_PROJECT_ID

Setup credentials (recommended):
  1. Run `./start-dev.sh` from the repo root — this generates
     app/orchestrator-agent/.env with real credentials fetched from AWS SSM.
  2. Run: cd app/orchestrator-agent && uv run pytest tests/integration/ -m integration -v --timeout=120

Alternative: create tests/integration/.env.integration with explicit overrides.

Skip by default: tests are marked @pytest.mark.integration
"""

import logging
import os
import uuid
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock

# ---------------------------------------------------------------------------
# Credential restoration: undo pytest-env fake values for integration tests
# ---------------------------------------------------------------------------
# pytest-env (configured in pyproject.toml) sets AWS_ACCESS_KEY_ID=testing etc.
# at startup, clobbering real credentials from the shell. We need to undo this
# so integration tests can use real provider credentials.
#
# Strategy:
#   1. Load .env.integration file if it exists (explicit credentials)
#   2. Load orchestrator .env (generated by start-dev.sh) if it exists
#   3. Otherwise, remove known fake values so SDKs fall back to default chains
#      (e.g., ~/.aws/credentials, az login, gcloud auth)

_ENV_INTEGRATION_FILE = Path(__file__).parent / ".env.integration"
_ORCHESTRATOR_ENV_FILE = Path(__file__).parent.parent.parent / ".env"

# Known fake values injected by pytest-env that must be removed/replaced
_FAKE_CREDENTIAL_VALUES = {
    "AWS_ACCESS_KEY_ID": "testing",
    "AWS_SECRET_ACCESS_KEY": "testing",
    "AWS_SECURITY_TOKEN": "testing",
    "AWS_SESSION_TOKEN": "testing",
    "AZURE_OPENAI_API_KEY": "test-key",
    "LANGSMITH_API_KEY": "test-key",
}


def _load_env_file(path: Path) -> dict[str, str]:
    """Parse a .env file into a dict (simple KEY=VALUE format)."""
    env_vars: dict[str, str] = {}
    if not path.exists():
        return env_vars
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip("'\"")
        if key:
            env_vars[key] = value
    return env_vars


def _restore_real_credentials() -> None:
    """Restore real credentials for integration tests.

    Priority:
    1. .env.integration file (test-specific overrides)
    2. Orchestrator .env file (generated by start-dev.sh with real SSM secrets)
    3. Remove fake values so SDKs fall back to default credential chains
    """
    # 1. Try .env.integration (explicit test overrides)
    env_overrides = _load_env_file(_ENV_INTEGRATION_FILE)
    if env_overrides:
        os.environ.update(env_overrides)
        logging.getLogger(__name__).info(f"Loaded {len(env_overrides)} env vars from {_ENV_INTEGRATION_FILE}")
        return

    # 2. Try orchestrator .env (generated by start-dev.sh)
    orchestrator_env = _load_env_file(_ORCHESTRATOR_ENV_FILE)
    if orchestrator_env:
        # Only inject credential-related vars, not all orchestrator config
        credential_keys = {
            "AZURE_OPENAI_API_KEY",
            "AZURE_OPENAI_ENDPOINT",
            "GCP_KEY",
            "GCP_PROJECT_ID",
            "GCP_LOCATION",
            "LANGSMITH_API_KEY",
            "LANGSMITH_ENDPOINT",
            "AWS_DEFAULT_REGION",
            "AWS_REGION",
        }
        injected = {k: v for k, v in orchestrator_env.items() if k in credential_keys}
        if injected:
            os.environ.update(injected)
            logging.getLogger(__name__).info(
                f"Loaded {len(injected)} credential vars from {_ORCHESTRATOR_ENV_FILE} (generated by start-dev.sh)"
            )

    # 3. Remove known fakes so SDKs use default credential chains
    for key, fake_value in _FAKE_CREDENTIAL_VALUES.items():
        if os.environ.get(key) == fake_value:
            del os.environ[key]
    logging.getLogger(__name__).info("Removed pytest-env fake credentials to allow default credential chains")


# Run at import time, BEFORE any credential detection code below
_restore_real_credentials()

# Enable LangSmith tracing for integration tests (pytest-env sets it to false)
# Must use direct assignment — setdefault won't override pytest-env's "false"
os.environ["LANGSMITH_TRACING"] = "true"
os.environ.setdefault("LANGSMITH_PROJECT", "integration-tests-orchestrator")

import pytest
from agent_common.models.base import ModelType, ThinkingLevel
from langgraph.checkpoint.memory import MemorySaver
from langgraph.store.memory import InMemoryStore
from pydantic import SecretStr

from app.core.agent import OrchestratorDeepAgent
from app.core.graph_factory import GraphFactory
from app.models.config import AgentSettings, UserConfig

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Credential detection helpers
# ---------------------------------------------------------------------------

ALL_MODELS: list[ModelType] = [
    "claude-sonnet-4.5",
    "claude-sonnet-4.6",
    "claude-haiku-4-5",
    "gpt-4o",
    "gpt-4o-mini",
    "gpt-5.4-mini",
    "gpt-5.4-nano",
    "gemini-3.1-pro-preview",
    "gemini-3-flash-preview",
]

BEDROCK_MODELS: list[ModelType] = ["claude-sonnet-4.5", "claude-sonnet-4.6", "claude-haiku-4-5"]
AZURE_MODELS: list[ModelType] = ["gpt-4o", "gpt-4o-mini", "gpt-5.4-mini", "gpt-5.4-nano"]
VERTEXAI_MODELS: list[ModelType] = ["gemini-3.1-pro-preview", "gemini-3-flash-preview"]

THINKING_MODELS: dict[ModelType, list[ThinkingLevel]] = {
    "claude-sonnet-4.5": [ThinkingLevel.minimal, ThinkingLevel.low, ThinkingLevel.medium],
    "claude-sonnet-4.6": [ThinkingLevel.minimal, ThinkingLevel.low, ThinkingLevel.medium],
    "gemini-3.1-pro-preview": [ThinkingLevel.low],
    "gemini-3-flash-preview": [ThinkingLevel.low],
}


def _has_bedrock_credentials() -> bool:
    """Check if valid AWS Bedrock credentials are available."""
    try:
        import boto3

        sts = boto3.client("sts", region_name=os.getenv("AWS_BEDROCK_REGION", os.getenv("AWS_REGION", "us-east-1")))
        sts.get_caller_identity()
        return True
    except Exception:
        return False


def _has_azure_credentials() -> bool:
    """Check if Azure OpenAI credentials are available."""
    endpoint = os.getenv("AZURE_OPENAI_ENDPOINT", "")
    api_key = os.getenv("AZURE_OPENAI_API_KEY", "")
    return bool(endpoint) and "openai.azure.com" in endpoint and bool(api_key) and api_key != "test-key"


def _has_vertexai_credentials() -> bool:
    """Check if Vertex AI credentials are available."""
    gcp_key = os.getenv("GCP_KEY", "")
    gcp_project = os.getenv("GCP_PROJECT_ID", "")
    # GCP_KEY must be a real service account JSON, not the empty default
    return bool(gcp_key) and gcp_key not in ("{}", "'{}'") and bool(gcp_project)


def _provider_for_model(model_type: ModelType) -> str:
    if model_type in BEDROCK_MODELS:
        return "bedrock"
    if model_type in AZURE_MODELS:
        return "azure"
    return "vertexai"


def _has_credentials_for(model_type: ModelType) -> bool:
    provider = _provider_for_model(model_type)
    if provider == "bedrock":
        return _has_bedrock_credentials()
    if provider == "azure":
        return _has_azure_credentials()
    return _has_vertexai_credentials()


# Cache credential checks (expensive - calls STS)
_credential_cache: dict[str, bool] = {}


def has_credentials(model_type: ModelType) -> bool:
    provider = _provider_for_model(model_type)
    if provider not in _credential_cache:
        _credential_cache[provider] = _has_credentials_for(model_type)
    return _credential_cache[provider]


# ---------------------------------------------------------------------------
# Skip markers
# ---------------------------------------------------------------------------

requires_bedrock = pytest.mark.skipif(
    not _has_bedrock_credentials(),
    reason="Bedrock credentials not available",
)

requires_azure = pytest.mark.skipif(
    not _has_azure_credentials(),
    reason="Azure OpenAI credentials not available",
)

requires_vertexai = pytest.mark.skipif(
    not _has_vertexai_credentials(),
    reason="Vertex AI credentials not available (need GCP_KEY + GCP_PROJECT_ID)",
)


def skip_marker_for(model_type: ModelType):
    """Return the appropriate skip marker for a given model type."""
    if model_type in BEDROCK_MODELS:
        return requires_bedrock
    if model_type in AZURE_MODELS:
        return requires_azure
    return requires_vertexai


# ---------------------------------------------------------------------------
# Module-level marker: all tests in this directory are integration tests
# ---------------------------------------------------------------------------

pytestmark = [pytest.mark.integration, pytest.mark.slow]


# ---------------------------------------------------------------------------
# LangSmith experiment metadata (used by langsmith pytest plugin)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def langsmith_experiment_metadata():
    """Attach metadata to the LangSmith experiment for this test run."""
    return {
        "environment": os.environ.get("ENV", "local"),
        "models": ", ".join(available_models() or ["none-available"]),
    }


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def memory_checkpointer():
    """In-memory checkpointer (replaces DynamoDB for tests)."""
    return MemorySaver()


@pytest.fixture(scope="session")
def memory_store():
    """In-memory store (replaces PostgreSQL + pgvector for tests)."""
    return InMemoryStore()


@pytest.fixture()
def context_id():
    """Unique context ID per test (conversation isolation)."""
    return f"test-ctx-{uuid.uuid4().hex[:12]}"


@pytest.fixture()
def test_user_config() -> UserConfig:
    """Minimal UserConfig for integration tests (no MCP tools, no remote agents)."""
    return UserConfig(
        user_id="integration-test-user",
        user_sub="integration-test-sub",
        access_token=SecretStr("fake-token-for-integration-tests"),
        name="Integration Test User",
        email="integration@test.local",
        language="en",
        timezone="Europe/Zurich",
        model=None,
        message_formatting="markdown",
        tools=[],
        sub_agents=[],
        local_subagents=[],
    )


@pytest.fixture(scope="session")
def patched_graph_factory(memory_checkpointer, memory_store):
    """Create a GraphFactory with in-memory checkpointer and store.

    Session-scoped so graphs are cached across tests (they are expensive to create).
    The checkpointer and store are also session-scoped.
    """
    settings = AgentSettings()

    factory = GraphFactory(config=settings, cost_logger=None)

    # Replace DynamoDB checkpointer and PostgreSQL store with in-memory versions
    factory._checkpointer = memory_checkpointer
    factory._store = memory_store
    factory._store_setup_complete = True

    # Pre-initialize static tools cache (avoids needing backend_factory)
    from app.core.time_tools import create_time_tool

    factory._static_tools_cache = [create_time_tool()]

    return factory


@pytest.fixture(scope="session")
def patched_agent(patched_graph_factory):
    """Create an OrchestratorDeepAgent with patched GraphFactory.

    Session-scoped so the agent (and its graphs) are reused across tests.
    """
    agent = OrchestratorDeepAgent.__new__(OrchestratorDeepAgent)
    agent.config = AgentSettings()
    agent._default_model_type = "claude-sonnet-4.5"
    agent._default_thinking_level = None
    agent._graph_factory = patched_graph_factory

    # Mock discovery services (no real tool/agent discovery in integration tests)
    agent.tool_discovery_service = MagicMock()
    agent.agent_discovery_service = MagicMock()

    # Stub OAuth2 client (not needed for streaming tests)
    agent.oauth2_client = MagicMock()

    return agent


@pytest.fixture()
def make_config(context_id, memory_checkpointer):
    """Factory fixture that creates a graph config dict for a given model type."""

    def _make(model_type: ModelType, thinking_level: ThinkingLevel | None = None) -> dict[str, Any]:
        return {
            "configurable": {
                "thread_id": context_id,
                "__pregel_checkpointer": memory_checkpointer,
            },
            "metadata": {
                "assistant_id": "integration-test-user",
                "user_id": "integration-test-user",
                "conversation_id": context_id,
                "user_name": "Integration Test",
                "model_type": model_type,
                "thinking_level": thinking_level,
            },
            "tags": ["integration-test"],
        }

    return _make


def available_models() -> list[ModelType]:
    """Return list of models for which credentials are available."""
    return [m for m in ALL_MODELS if has_credentials(m)]


def one_model_per_provider() -> list[ModelType]:
    """Return one model per provider for which credentials are available."""
    result: list[ModelType] = []
    for models in [BEDROCK_MODELS[:1], AZURE_MODELS[:1], VERTEXAI_MODELS[:1]]:
        for m in models:
            if has_credentials(m):
                result.append(m)
    return result
