---
- name: 'build and push the Orchestrator Agent Docker image to ECR'
  include_role:
    name: 'ringier.aws_cicd.build_push_docker_image'
  vars:
    ecr_repository_name: '{{ orchestrator_agent_ecr_repository_name }}'
    code_path: '{{ playbook_dir }}/../app/orchestrator-agent'
    adhoc_deploy: true

- name: 'set orchestrator agent docker image fact'
  set_fact:
    orchestrator_agent_docker_image: '{{ docker_image_full_name_and_tag }}'

- name: 'set cloudformation template'
  set_fact:
    cloudformation_template: '{{ role_path }}/files/cf-ecs.yml'

- name: 'deploy the ECS and adjacent resources'
  include_role:
    name: 'ringier.aws_cicd.run_cloudformation'
  vars:
    stack_name: '{{ env }}-{{ project_id }}-{{ software_component }}-orchestrator-ecs'
    template: '{{ cloudformation_template }}'
