- name: 'get the gatana service user credentials from the vault'
  set_fact:
    gatana_api_key_obj: '{{ gatana_api_key }}'

- name: 'upsert the Gatana credentials into SSM parameter store'
  no_log: '{{ ansible_verbosity < 3 }}'
  ringier.aws_cicd.ssm_parameter:
    overwrite_value: 'changed'
    region: '{{ aws_region }}'
    name: '{{ ssmkey_gatana_api_key }}'
    description: 'Gatana API credentials for {{ project_id }}'
    string_type: 'SecureString'
    key_id: 'alias/gov-rcplus-devops-secrets'
    value: '{{ gatana_api_key_obj }}'
    tags:
      Name: '{{ env }}-{{ project_id }}-{{ software_component }}-gatana-api-key'
      Project: '{{ project_id }}'
      Environment: '{{ env }}'
      Repository: '{{ git_info.repo_name }}'
      Version: '{{ project_version }}'

- name: 'get the langsmith api key from the vault'
  set_fact:
    langsmith_api_key_obj: '{{ langsmith_api_key }}'

- name: 'upsert the Langsmith credentials into SSM parameter store'
  no_log: '{{ ansible_verbosity < 3 }}'
  ringier.aws_cicd.ssm_parameter:
    overwrite_value: 'changed'
    region: '{{ aws_region }}'
    name: '{{ ssmkey_langsmith_api_key }}'
    description: 'Langsmith API credentials for {{ project_id }}'
    string_type: 'SecureString'
    key_id: 'alias/gov-rcplus-devops-secrets'
    value: '{{ langsmith_api_key_obj }}'
    tags:
      Name: '{{ env }}-{{ project_id }}-{{ software_component }}-langsmith-api-key'
      Project: '{{ project_id }}'
      Environment: '{{ env }}'
      Repository: '{{ git_info.repo_name }}'
      Version: '{{ project_version }}'
